development:
  access_key: 37046a41354fb511e6b3
  secret_key: 0264798fcef742ccf608
  cloud_id: 3cf7a094467ed995fc841b163f006ec2
  # Uncomment the line below if your account is in the EU
  api_host: api-eu.pandastream.com
test:
  access_key: 37046a41354fb511e6b3
  secret_key: 0264798fcef742ccf608
  cloud_id: 3cf7a094467ed995fc841b163f006ec2
  # Uncomment the line below if your account is in the EU
  api_host: api-eu.pandastream.com
production:
  access_key: 37046a41354fb511e6b3
  secret_key: 0264798fcef742ccf608
  cloud_id: 3cf7a094467ed995fc841b163f006ec2
  # Uncomment the line below if your account is in the EU
  api_host: api-eu.pandastream.com